### ISSUE TITLE
Content license instead of code license

### ISSUE THREAD

**Issue by Ana06** [RomuloOliveira/commit-messages-guide#4]
Great guide! :heart: 

I think there is an issue with the license. This is not software, but documentation. I think that the Apache license doesn't apply and that you should use a content license, such as [CC-BY-4.0](https://choosealicense.com/licenses/cc-by-4.0).

Check: https://choosealicense.com/non-software

It may be great that you update it :wink:

**Comment by RomuloOliveira** [comment]
Hi @Ana06, thank you! I'll change the license, CC-BY-4.0 looks good to me, I didn't knew this license, thanks.

**Comment by Ana06** [comment]
:heart:
