### ISSUE TITLE
Add vietnamese version for this guide

### ISSUE THREAD

**Issue by lploc94** [RomuloOliveira/commit-messages-guide#45]
Hi, I see this guide is very helpful, but the truth that there are a few Vietnamese peoples know this guide. I want to translate this guide to Vietnamese so that it can be popular in Vietnamese developer community. I have read CONTRIBUTING.md carefuly. I hope I can help by adding a README_vi-VI.md file for Vietnamese version.

**Comment by RomuloOliveira** [comment]
Hi, @lploc94, a translation was made at #37 but unfortunately the author has closed the PR and deleted the repository. I have a backup of the Vietnamese translation, though.

Would this help you? I can open a new pull request with his translation and you could help with review and making changes.

**Comment by RomuloOliveira** [comment]
Just did that #46

**Comment by lploc94** [comment]
Hi, I have some change at my company then I forgot to check my Github. I have added a new pull request.
