### ISSUE TITLE
Remove Chris Beams 'help sentence' in favor of the imperative

### ISSUE THREAD

**Issue by McNetic** [RomuloOliveira/commit-messages-guide#69]
Almost all sources regarding the commit summary message suggest using the imperative. Unfortunately, in his otherwise very nice and often cited article on commit message, while also advocating the imperative, Chris Beams made the mistake to suggest that a commit message should also be able to complete his "help sentence": `If applied, this commit will ...`.

As the imperative in English is always the same as the infinitive, imperative summaries used in this way will correctly complete the sentence with the english will future form (but will no longer be imperative).

This does not work at all in many (probably most) other languages, however. Although being cited on numerous places, it leads to confusion as soon as languages other then english are used (for example, in this guide, in the german version, the example sentences are like `Korrigiert den Methodennamen der InventoryBackend Kind-Klassen` which is not imperative (imperative would be 'Korrigiere den Methodennamen der InventoryBackend Kind-Klassen`).

As in other languages, using a help sentence as advocated by Chris beams would lead to grammatically totally different forms of summaries, I suggest completely removing the 'help sentence' from the guide.

**Comment by RomuloOliveira** [comment]
Hi, @McNetic, thanks for raising this out! Makes a lot of sense and I haven't saw it in that way.

Taking Portuguese (my first language) as example, I even think now that what would better the describe the verb would be the equivalent to simple present (`Corrige o nome do método das classes filhas InventoryBackend` or `Korrigieren Sie den Methodennamen der untergeordneten InventoryBackend-Klassen` if Google translator worked correctly).

Even though it's same as imperative, it's a description of what it **does** and not what it should do (`[Este commit] Corrige o nome do método` or `[This commit] Fixes the method name`). And of course, this is the opposite of what is in this guide.

If you or other folks have a suggestion on this matter, feel free to drop!

Anyway, I'll remove the help sentence as this won't apply to other languages.

**Comment by RomuloOliveira** [comment]
Fixed by #70
