### ISSUE TITLE
Does not mention the drawbacks of rebase and squashes

### ISSUE THREAD

**Issue by cefigueiredo** [RomuloOliveira/commit-messages-guide#8]
I really like the guide. My only concerns are on the recommendation of squashes and rebases without mention the drawbacks of change the history.

May I patch some comments on this subject? 

If I do, I will need help translating it to Deutsch.

**Comment by RomuloOliveira** [comment]
@cefigueiredo Hi, first of all, thank you for reporting this. Please feel free to open a Pull Request on this, I'll help you with Deutsch and Portuguese translation.

**Comment by RomuloOliveira** [comment]
Fixed in #9
